<?php

include('includes/mixpanel.node.inc');
include('includes/mixpanel.user.inc');
include('includes/mixpanel.comment.inc');
include('includes/mixpanel.og.inc');

/**
 * Implementation of hook_form_alter().
 */
function mixpanel_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'contact_mail_user':
      $form['#submit'][] = "mixpanel_contact_mail_user_submit";
      break;
    case 'user_profile_form':
      $form['#submit'][] = "mixpanel_user_profile_form_submit";
      break;
    case 'search_theme_form':
      $form['#submit'][] = "mixpanel_search_theme_form_submit";
      break;
  }
}

