<?php

include('includes/mixpanel_defaults.node.inc');
include('includes/mixpanel_defaults.user.inc');
include('includes/mixpanel_defaults.comment.inc');
include('includes/mixpanel_defaults.og.inc');

/**
 * Implementation of hook_init().
 */
function mixpanel_init() {
  // Track visits to user pages.
  if (arg(0) == "user" && is_numeric(arg(1))) {
    mixpanel_track("user-view-profile", array('visited-user' => arg(1)));
  }
}

/**
 * Implementation of hook_form_alter().
 */
function mixpanel_defaults_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'contact_mail_user':
      $form['#submit'][] = "mixpanel_defaults_contact_mail_user_submit";
      break;
    case 'user_profile_form':
      $form['#submit'][] = "mixpanel_defaults_user_profile_form_submit";
      break;
    case 'search_theme_form':
      $form['#submit'][] = "mixpanel_defaults_search_theme_form_submit";
      break;
  }
}

